
package com.oa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkflowServiceXml", targetNamespace = "http://webservices.workflow.weaver", wsdlLocation = "http://192.168.12.66/services/WorkflowServiceXml?wsdl")
public class WorkflowServiceXml
    extends Service
{

    private final static URL WORKFLOWSERVICEXML_WSDL_LOCATION;
    private final static WebServiceException WORKFLOWSERVICEXML_EXCEPTION;
    private final static QName WORKFLOWSERVICEXML_QNAME = new QName("http://webservices.workflow.weaver", "WorkflowServiceXml");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.12.66/services/WorkflowServiceXml?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKFLOWSERVICEXML_WSDL_LOCATION = url;
        WORKFLOWSERVICEXML_EXCEPTION = e;
    }

    public WorkflowServiceXml() {
        super(__getWsdlLocation(), WORKFLOWSERVICEXML_QNAME);
    }

    public WorkflowServiceXml(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKFLOWSERVICEXML_QNAME, features);
    }

    public WorkflowServiceXml(URL wsdlLocation) {
        super(wsdlLocation, WORKFLOWSERVICEXML_QNAME);
    }

    public WorkflowServiceXml(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKFLOWSERVICEXML_QNAME, features);
    }

    public WorkflowServiceXml(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowServiceXml(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WorkflowServiceXmlPortType
     */
    @WebEndpoint(name = "WorkflowServiceXmlHttpPort")
    public WorkflowServiceXmlPortType getWorkflowServiceXmlHttpPort() {
        return super.getPort(new QName("http://webservices.workflow.weaver", "WorkflowServiceXmlHttpPort"), WorkflowServiceXmlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowServiceXmlPortType
     */
    @WebEndpoint(name = "WorkflowServiceXmlHttpPort")
    public WorkflowServiceXmlPortType getWorkflowServiceXmlHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.workflow.weaver", "WorkflowServiceXmlHttpPort"), WorkflowServiceXmlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKFLOWSERVICEXML_EXCEPTION!= null) {
            throw WORKFLOWSERVICEXML_EXCEPTION;
        }
        return WORKFLOWSERVICEXML_WSDL_LOCATION;
    }

}
