
package com.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkflowServiceXmlPortType", targetNamespace = "http://webservices.workflow.weaver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkflowServiceXmlPortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "forward2WorkflowRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.Forward2WorkflowRequest")
    @ResponseWrapper(localName = "forward2WorkflowRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.Forward2WorkflowRequestResponse")
    public String forward2WorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        String in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getAllWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetAllWorkflowRequestList")
    @ResponseWrapper(localName = "getAllWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetAllWorkflowRequestListResponse")
    public ArrayOfString getAllWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getWorkflowRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequest")
    @ResponseWrapper(localName = "getWorkflowRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequestResponse")
    public String getWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getHendledWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetHendledWorkflowRequestList")
    @ResponseWrapper(localName = "getHendledWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetHendledWorkflowRequestListResponse")
    public ArrayOfString getHendledWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getToDoWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetToDoWorkflowRequestList")
    @ResponseWrapper(localName = "getToDoWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetToDoWorkflowRequestListResponse")
    public ArrayOfString getToDoWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getWorkflowRequest4split")
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getWorkflowRequest4split", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequest4Split")
    @ResponseWrapper(localName = "getWorkflowRequest4splitResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequest4SplitResponse")
    public String getWorkflowRequest4Split(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "submitWorkflowRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.SubmitWorkflowRequest")
    @ResponseWrapper(localName = "submitWorkflowRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.SubmitWorkflowRequestResponse")
    public String submitWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        String in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetHendledWorkflowRequestCount")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetHendledWorkflowRequestCountResponse")
    public int getHendledWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getLeaveDays", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetLeaveDays")
    @ResponseWrapper(localName = "getLeaveDaysResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetLeaveDaysResponse")
    public String getLeaveDays(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        String in4);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCreateWorkflowList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowList")
    @ResponseWrapper(localName = "getCreateWorkflowListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowListResponse")
    public ArrayOfString getCreateWorkflowList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCreateWorkflowCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowCount")
    @ResponseWrapper(localName = "getCreateWorkflowCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowCountResponse")
    public int getCreateWorkflowCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetProcessedWorkflowRequestCount")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetProcessedWorkflowRequestCountResponse")
    public int getProcessedWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "forwardWorkflowRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.ForwardWorkflowRequest")
    @ResponseWrapper(localName = "forwardWorkflowRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.ForwardWorkflowRequestResponse")
    public String forwardWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        String in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "doCreateWorkflowRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DoCreateWorkflowRequest")
    @ResponseWrapper(localName = "doCreateWorkflowRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DoCreateWorkflowRequestResponse")
    public String doCreateWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "doForceOver", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DoForceOver")
    @ResponseWrapper(localName = "doForceOverResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DoForceOverResponse")
    public String doForceOver(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCCWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCCWorkflowRequestCount")
    @ResponseWrapper(localName = "getCCWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCCWorkflowRequestCountResponse")
    public int getCCWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetProcessedWorkflowRequestList")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetProcessedWorkflowRequestListResponse")
    public ArrayOfString getProcessedWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getAllWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetAllWorkflowRequestCount")
    @ResponseWrapper(localName = "getAllWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetAllWorkflowRequestCountResponse")
    public int getAllWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCreateWorkflowRequestInfo", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowRequestInfo")
    @ResponseWrapper(localName = "getCreateWorkflowRequestInfoResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowRequestInfoResponse")
    public String getCreateWorkflowRequestInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getMyWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetMyWorkflowRequestList")
    @ResponseWrapper(localName = "getMyWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetMyWorkflowRequestListResponse")
    public ArrayOfString getMyWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCreateWorkflowTypeList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowTypeList")
    @ResponseWrapper(localName = "getCreateWorkflowTypeListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowTypeListResponse")
    public ArrayOfString getCreateWorkflowTypeList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getMyWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetMyWorkflowRequestCount")
    @ResponseWrapper(localName = "getMyWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetMyWorkflowRequestCountResponse")
    public int getMyWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getWorkflowNewFlag", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowNewFlag")
    @ResponseWrapper(localName = "getWorkflowNewFlagResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowNewFlagResponse")
    public ArrayOfString getWorkflowNewFlag(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     */
    @WebMethod
    @RequestWrapper(localName = "writeWorkflowReadFlag", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.WriteWorkflowReadFlag")
    @ResponseWrapper(localName = "writeWorkflowReadFlagResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.WriteWorkflowReadFlagResponse")
    public void writeWorkflowReadFlag(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetToDoWorkflowRequestCount")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetToDoWorkflowRequestCountResponse")
    public int getToDoWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "givingOpinions", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GivingOpinions")
    @ResponseWrapper(localName = "givingOpinionsResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GivingOpinionsResponse")
    public String givingOpinions(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        String in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCreateWorkflowTypeCount", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowTypeCount")
    @ResponseWrapper(localName = "getCreateWorkflowTypeCountResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCreateWorkflowTypeCountResponse")
    public int getCreateWorkflowTypeCount(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfWorkflowRequestLog
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getWorkflowRequestLogs", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequestLogs")
    @ResponseWrapper(localName = "getWorkflowRequestLogsResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetWorkflowRequestLogsResponse")
    public ArrayOfWorkflowRequestLog getWorkflowRequestLogs(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        int in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.DeleteRequestResponse")
    public boolean deleteRequest(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns com.oa.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getCCWorkflowRequestList", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCCWorkflowRequestList")
    @ResponseWrapper(localName = "getCCWorkflowRequestListResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetCCWorkflowRequestListResponse")
    public ArrayOfString getCCWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://webservices.workflow.weaver")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://webservices.workflow.weaver")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservices.workflow.weaver")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservices.workflow.weaver")
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://webservices.workflow.weaver", className = "com.oa.GetUserIdResponse")
    public String getUserId(
        @WebParam(name = "in0", targetNamespace = "http://webservices.workflow.weaver")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservices.workflow.weaver")
        String in1);

}
